
import React from 'react'
import { supabase } from '../lib/supabase'
import Nav from '../components/Nav'

type Cafe = { id: string, name: string }

export default function OwnerDashboard() {
  const [cafes, setCafes] = React.useState<Cafe[]>([])
  const [name, setName] = React.useState('')
  const [pin, setPin] = React.useState('')
  const [stats, setStats] = React.useState<{today:number, week:number, month:number} | null>(null)

  React.useEffect(() => {
    (async () => {
      const { data: me }: any = await (supabase as any).from('profiles').select('id,role').eq('id', (await (supabase as any).auth.getUser()).data.user?.id).single()
      if (me?.role !== 'owner') {
        alert('You are not an owner. Ask support to upgrade your role.')
      }
      await loadCafes()
    })()
  }, [])

  async function loadCafes() {
    const { data: c }: any = await (supabase as any).from('cafes').select('id,name').order('created_at', { ascending: true })
    setCafes(c || [])
  }

  async function createCafe() {
    if (!name || !pin) return alert('Name and PIN required')
    const { data: inserted, error }: any = await (supabase as any).from('cafes').insert({ name, owner_id: (await (supabase as any).auth.getUser()).data.user?.id }).select('id').single()
    if (error) return alert(error.message)
    const cafe_id = inserted.id
    // store settings with bcrypt hash generated by Postgres if available, else plaintext in demo
    const hashRes: any = await (supabase as any).rpc?.('gen_hash', { raw: pin })
    if (hashRes && !hashRes.error && hashRes.data) {
      await (supabase as any).from('cafe_settings').insert({
        cafe_id, barista_pin_hash: hashRes.data, points_per_purchase: 1, redeem_threshold: 10
      })
    } else {
      // demo fallback
      await (supabase as any).from('cafe_settings').insert({
        cafe_id, barista_pin_hash: pin, points_per_purchase: 1, redeem_threshold: 10
      })
    }
    setName(''); setPin(''); loadCafes()
  }

  async function fetchStats(cafe_id: string) {
    const t: any = await (supabase as any).rpc('count_tx', { cafe: cafe_id, win: 'day' })
    const w: any = await (supabase as any).rpc('count_tx', { cafe: cafe_id, win: 'week' })
    const m: any = await (supabase as any).rpc('count_tx', { cafe: cafe_id, win: 'month' })
    setStats({ today: t.data||0, week: w.data||0, month: m.data||0 })
  }

  return (
    <div className="container">
      <Nav role="owner" />
      <div className="row">
        <div className="card" style={{ flex: 1, minWidth: 280 }}>
          <h3>Create café</h3>
          <div className="row">
            <input placeholder="Café name" value={name} onChange={e=>setName(e.target.value)} />
            <input placeholder="Barista PIN (4 digits)" value={pin} onChange={e=>setPin(e.target.value)} />
            <button className="button" onClick={createCafe}>Create</button>
          </div>
          <p className="small">After creating, print the QR: <code>/scan?cafe=&lt;cafe_id&gt;</code></p>
        </div>
        <div className="card" style={{ flex: 2, minWidth: 280 }}>
          <h3>Your cafés</h3>
          <table>
            <thead><tr><th>Name</th><th>QR</th><th>Print</th><th>Stats</th></tr></thead>
            <tbody>
              {cafes.map(c => (
                <tr key={c.id}>
                  <td>{c.name}</td>
                  <td><a target="_blank" href={`/scan?cafe=${c.id}`}>Open QR link</a></td>
                  <td><a className="button" target="_blank" href={`/owner/qr?cafe=${c.id}&name=${encodeURIComponent(c.name)}`}>Print QR</a></td>
                  <td><button className="button" onClick={() => fetchStats(c.id)}>View</button></td>
                </tr>
              ))}
            </tbody>
          </table>
          {stats && (
            <div className="small" style={{marginTop:12}}>
              <div>Today: <strong>{stats.today}</strong> stamps</div>
              <div>This week: <strong>{stats.week}</strong> stamps</div>
              <div>This month: <strong>{stats.month}</strong> stamps</div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
